#! /bin/sh

pkill sxhkd; sxhkd &
feh --bg-tile $WALLPAPER
#pkill compton; compton -b

# Style settings (have to be applied before assigning desktops)
bspc config border_width		2
bspc config window_gap			36

# Portable monitor config
readarray -t monitors <<< $(xrandr |grep " connected [[:digit:]]" | awk '{print $1}')
num_monitors=${#monitors[@]}
if [[ $num_monitors < "$(bspc query -M | wc -l)" ]]; then
	echo case
	for i in {1..9}
	do
		bspc desktop "$i" -m ${monitors[0]}
	done
fi
bspc monitor -o 1 2 3 4 5 6 7 8 9
if [[ $num_monitors > 2 ]]; then
	bspc monitor ${monitors[0]} -d 1 4 7
	bspc monitor ${monitors[1]} -d 2 5 8
	bspc monitor ${monitors[2]} -d 3 6 9
elif [[ $num_monitors -eq 2 ]]; then
	bspc monitor ${monitors[0]} -d 1 3 5 7 9
	bspc monitor ${monitors[1]} -d 2 4 6 8
else
	bspc monitor -d 1 2 3 4 5 6 7 8 9
fi

# Prevents cursor from being just an 'x'
xsetroot -cursor_name left_ptr

bspc config borderless_monocle 		true
bspc config gapless_monocle      	true
bspc config split_ratio          	0.50

bspc config focus_follows_pointer 	true
bspc config pointer_follows_focus 	false
#bspc config focus_by_distance    	true
#bspc config history_aware_focus  	true

bspc config active_border_color \#000000
bspc config normal_border_color \#eeeeee

bspc rule -a "*" border=off
bspc rule -a st-256color border=on
bspc rule -a TelegramDesktop state=floating
bspc rule -a Pavucontrol state=floating
