#! /bin/sh

pkill sxhkd; sxhkd &
feh --bg-fill $WALLPAPER
pkill compton; compton -b

# Style settings (have to be applied before assigning desktops)
bspc config border_width		2
bspc config window_gap			36

# Host specific monitor configuration
if [[ $(hostname) == desk* ]]; then
	bspc monitor -f HDMI1
	bspc monitor -d 1 3 5 7 9
	bspc monitor -f VGA1
	bspc monitor -d 2 4 6 8
	bspc desktop -f 1

else
	if [[ $(hostname) == nyla ]]; then
		bspc config window_gap		75
	fi
	bspc monitor -d 1 2 3 4 5 6 7 8 9
fi

# Prevents cursor from being just an 'x'
xsetroot -cursor_name left_ptr

bspc config borderless_monocle 		true
bspc config gapless_monocle      	true
bspc config split_ratio          	0.50

bspc config focus_follows_pointer 	true
bspc config pointer_follows_focus 	false
bspc config focus_by_distance    	true
bspc config history_aware_focus  	true

bspc config active_border_color \#000000
bspc config normal_border_color \#e0e0e0

bspc rule -a "*" border=off
bspc rule -a st-256color border=on
bspc rule -a TelegramDesktop state=floating
bspc rule -a Pavucontrol state=floating
